### ISSUE TITLE
work need to init it repeatedly

### ISSUE THREAD

**Issue by xtbwqtq** [TomBric/aircraft-trim-indicator#1]
What is the reason why I have to call these methods every time I want to display data correctly on the screen in order for it to work, and this will cause my screen to flicker and give the illusion that something is wrong, when in fact it's working properly:
`
self.e.init(False)
`
`
self.e.clear(0xFF)  # necessary to overwrite everything
`
`
self.e.init(True)
`
`
self.e.clear(0xFF)  # necessary to overwrite everything
`

**Comment by TomBric** [comment]
Hi,
this "init" sequence is only used, when the display is started at the beginning. It clears the screen.
But you use it only once. Later the display is only used by:  
        d.indicator(....)    # this prepares the framebuffer   
        d.print()       # this actually prints the new framebuffer on the screen

**Comment by xtbwqtq** [comment]
> Hi, this "init" sequence is only used, when the display is started at the beginning. It clears the screen. But you use it only once. Later the display is only used by: d.indicator(....) # this prepares the framebuffer d.print() # this actually prints the new framebuffer on the screen

![image](https://github.com/TomBric/aircraft-trim-indicator/assets/146714110/bf397bc6-e983-402b-876d-2e6e9ce5b469)

_display.indicator()
 _display.text("{:.2f}℃".format(temperature), 5, 50, 32)
_display.text("{:.2f}%".format(humidity), 50, 130, 24)
_display.display_part()

**Comment by xtbwqtq** [comment]
> Hi, this "init" sequence is only used, when the display is started at the beginning. It clears the screen. But you use it only once. Later the display is only used by: d.indicator(....) # this prepares the framebuffer d.print() # this actually prints the new framebuffer on the screen

I have made the following changes to your code, and it seems to work properly (except that the black pixels are not so obvious at first, and will become clear after a few refreshes)：

![image](https://github.com/TomBric/aircraft-trim-indicator/assets/146714110/c4c0e5c4-7fd7-485d-82de-c7f1e3edbcb6)
_display.indicator()
_display.text("{:.2f}℃".format(temperature), 5, 50, 32)
_display.text("{:.2f}%".format(humidity), 50, 130, 24)
 _display.display_part()

**Comment by TomBric** [comment]
This is normal. The display needs some refreshes at the beginning to be really visible.
So everything is fine.
